version: "3"

services:
  dberp:
    image: postgres
    container_name: dberp
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks: 
      - apierp
    volumes:
      - dberp-data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3333:3333"
    env_file: .env
    environment: 
      POSTGRES_HOST: dberp
    volumes: 
      - .:/usr/app
    container_name: api
    restart: always
    depends_on:
      - dberp
    networks: 
      - apierp
    command: yarn start:prod

networks:
  apierp:
    driver: bridge

volumes:
  .:
  dberp-data: